pipeline {
  agent {
    docker { 
      image 'bentolor/docker-dind-awscli:2.3.4'
      args '--user=root -v /var/run/docker.sock:/var/run/docker.sock'
      label 'linux' 
      }
    }
  stages {
    stage('Build and Push') {
      when {
        anyOf { 
          branch 'main'; 
          branch 'develop';
          branch 'feature/*';
          branch 'bugfix/*';
          branch 'hotfix/*';
          branch 'release/*'
          }
      }
      steps {
        echo "Build number is ${currentBuild.number}"
        withCredentials([
          [
            $class: 'AmazonWebServicesCredentialsBinding',
            credentialsId: 'AIS-AWS',
            accessKeyVariable: 'AWS_ACCESS_KEY_ID',
            secretKeyVariable: 'AWS_SECRET_ACCESS_KEY',
            stsTokenDuration: 7200
          ]
        ]) 
        
        {
          sh '''#!/bin/bash
          apk add --update alpine-sdk && apk add --no-cache --update libffi-dev openssl-dev build-base git git-lfs
          '''
          sh '''#!/bin/bash
	        git submodule update --init --recursive
          git submodule foreach "git fetch"
          git submodule foreach "git lfs pull"
          '''
          sh '''#!/bin/bash
          make docker-stop-dev
          '''
          sh '''#!/bin/bash
          make docker-prune
          '''
          sh '''#!/bin/bash
          export TAG=`echo $GIT_BRANCH | tr / -`
          echo ${TAG}
          make TAG="${TAG}"
          make docker-build-base
          '''
          sh '''#!/bin/bash
          export TAG=`echo $GIT_BRANCH | tr / -`
          make TAG="${TAG}"
          make docker-build-dev
          '''
          sh '''#!/bin/bash
          export TAG=`echo $GIT_BRANCH | tr / -`
          # make TAG="${TAG}"
          # make docker-build-prod
          '''
          sh '''#!/bin/bash
          export TAG=`echo $GIT_BRANCH | tr / -`
          make TAG="${TAG}"
          make docker-login
          make dockerhub-login
          make docker-push-base
          '''
          sh '''#!/bin/bash
          export TAG=`echo $GIT_BRANCH | tr / -`
          make TAG="${TAG}"
          make docker-login
          make dockerhub-login
          make docker-push-dev
          '''
          sh '''#!/bin/bash
          export TAG=`echo $GIT_BRANCH | tr / -`
          make TAG="${TAG}"
          # make docker-login
          # make docker-push-prod
          '''
          sh '''#!/bin/bash
          make docker-stop-dev
          '''
          sh '''#!/bin/bash
          make docker-prune
          '''
        }
      }
    }
      stage('tag') {
        when { tag 'v*' }
        steps {
          echo "Build number is ${currentBuild.number}"
          withCredentials([
            [
              $class: 'AmazonWebServicesCredentialsBinding',
              credentialsId: 'AIS-AWS',
              accessKeyVariable: 'AWS_ACCESS_KEY_ID',
              secretKeyVariable: 'AWS_SECRET_ACCESS_KEY',
              stsTokenDuration: 7200
           ]
          ]) {
          sh '''#!/bin/bash
          apk add --update alpine-sdk && apk add --no-cache --update libffi-dev openssl-dev build-base git git-lfs
          '''
          sh '''#!/bin/bash
          git submodule foreach "git fetch"
          git submodule foreach "git lfs pull"
          '''
          sh '''#!/bin/bash
          make docker-stop-dev
          '''
          sh '''#!/bin/bash
          make docker-prune
          '''
          sh '''#!/bin/bash
          export TAG=`echo $GIT_BRANCH | tr / -`
          echo ${TAG}
          make TAG="${TAG}"
          make docker-build-base
          '''
          sh '''#!/bin/bash
          export TAG=`echo $GIT_BRANCH | tr / -`
          make TAG="${TAG}"
          make docker-build-dev
          '''
          sh '''#!/bin/bash
          export TAG=`echo $GIT_BRANCH | tr / -`
          make TAG="${TAG}"
          make docker-build-prod
          '''
          sh '''#!/bin/bash
          export TAG=`echo $GIT_BRANCH | tr / -`
          make TAG="${TAG}"
          make docker-login
          make dockerhub-login
          make docker-push-base
          '''
          sh '''#!/bin/bash
          export TAG=`echo $GIT_BRANCH | tr / -`
          make TAG="${TAG}"
          make docker-login
          make dockerhub-login
          make docker-push-dev
          '''
          sh '''#!/bin/bash
          export TAG=`echo $GIT_BRANCH | tr / -`
          make TAG="${TAG}"
          make docker-login
          make dockerhub-login
          make docker-push-prod
          '''
          sh '''#!/bin/bash
          make docker-stop-dev
          '''
          sh '''#!/bin/bash
          make docker-prune
          '''
        }
       }
    }

    stage('Pull requests') {
      when {
        branch 'PR-*'
      }
      steps {
        echo "Build number is ${currentBuild.number}"
        withCredentials([
          [
            $class: 'AmazonWebServicesCredentialsBinding',
            credentialsId: 'AIS-AWS',
            accessKeyVariable: 'AWS_ACCESS_KEY_ID',
            secretKeyVariable: 'AWS_SECRET_ACCESS_KEY',
            stsTokenDuration: 7200
          ]
        ]) {
          sh '''#!/bin/bash
          apk add --update alpine-sdk && apk add --no-cache --update libffi-dev openssl-dev build-base git git-lfs
          '''
          sh '''#!/bin/bash
          git submodule foreach "git fetch"
          git submodule foreach "git lfs pull"
          '''
          sh '''#!/bin/bash
          make docker-stop-dev
          '''
          sh '''#!/bin/bash
          make docker-prune
          '''
          sh '''#!/bin/bash
          export TAG=`echo $GIT_BRANCH | tr / -`
          echo ${TAG}
          make TAG="${TAG}"
          make docker-build-base
          '''
          sh '''#!/bin/bash
          export TAG=`echo $GIT_BRANCH | tr / -`
          make TAG="${TAG}"
          make docker-build-dev
          '''
          sh '''#!/bin/bash
          export TAG=`echo $GIT_BRANCH | tr / -`
          # make TAG="${TAG}"
          # make docker-build-prod
          '''
          sh '''#!/bin/bash
          export TAG=`echo $GIT_BRANCH | tr / -`
          make TAG="${TAG}"
          make docker-login
          make dockerhub-login
          make docker-push-base
          '''
          sh '''#!/bin/bash
          export TAG=`echo $GIT_BRANCH | tr / -`
          make TAG="${TAG}"
          make docker-login
          make dockerhub-login
          make docker-push-dev
          '''
          sh '''#!/bin/bash
          export TAG=`echo $GIT_BRANCH | tr / -`
          # make TAG="${TAG}"
          # make docker-login
          # make dockerhub-login
          # make docker-push-prod
          '''
          sh '''#!/bin/bash
          export TAG=`echo $GIT_BRANCH | tr / -`
          echo ${TAG}
          make TAG="${TAG}"
          make docker-login
          make dockerhub-login
          make docker-pull-dev
          # make docker-start-gtest
          # sleep 10
          # make docker-run-g-test
          '''
          sh '''#!/bin/bash
          export TAG=`echo $GIT_BRANCH | tr / -`
          echo ${TAG}
          # make TAG="${TAG}"
          # make docker-login
          # make docker-pull-dev
          # make docker-start-headless
          # sleep 10
          # make docker-run-sim-test
          '''
          sh '''#!/bin/bash
          make docker-stop-dev
          '''
          sh '''#!/bin/bash
          make docker-prune
          '''
        }
      }
    }
  }

  post {
    always {
      echo currentBuild.currentResult
      cleanWs()
    }
  }

  options {
    buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '5', daysToKeepStr: '', numToKeepStr: '5'))
    disableConcurrentBuilds()
  }
}
