ARG BASE_IMAGE
FROM ${BASE_IMAGE}

WORKDIR /opt

ARG DEBIAN_FRONTEND=noninteractive

ARG PROJECT
ENV HOME_DIR /root
ENV WORKSPACE ${HOME_DIR}

# Copy project
ADD robot_ws ${WORKSPACE}/robot_ws
ADD .git ${WORKSPACE}

RUN /bin/bash -c ' \
            . /opt/ros/noetic/setup.bash && \
            cd ${WORKSPACE}/robot_ws/ && \
            rm -rf build install logs && \
            colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release --merge-install --install-base /opt/${PROJECT} &&\
            . /opt/${PROJECT}/setup.bash'

WORKDIR ${WORKSPACE}

COPY binder/dev/bashrc /tmp/bashrc
COPY binder/dev/Makefile /root/phoenix1/Makefile
COPY binder/dev/Makefile ${HOME}/${PROJECT}/Makefile

COPY binder/dev/workspace.sh /opt/${PROJECT}/.env.sh
COPY binder/ade/entrypoint /tmp/entrypoint
ENTRYPOINT ["/tmp/entrypoint"]
CMD ["/bin/sh", "-c", "trap 'exit 147' TERM; tail -f /dev/null & wait ${!}"]
